[package]
name = "xorcism"
version = "0.1.0"
authors = ["Ben Herzog"]

[target.x86_64-pc-windows-gnu]
linker = "/usr/bin/x86_64-w64-mingw32-gcc"

[dependencies]
itertools = "0.7.3"
counter = "0.4.3"
derive_more = "0.13.0"
clap = "2.32.0"
rayon = "1.0.3"
